version: "3.5"
services:
  

  apache2:
    image: integ1:5000/agrica/rhel7-apache24-php55-oidc:latest
    container_name: apache246
    environment:
      APACHE_APP_DIR: "/DATA/app"
      APACHE_LOG_DIR: "/var/log/httpd/app"
      HOST_IP: "localhost"
      HOST_PORT: "80"
      FPM_HOST: "fpm"
    volumes:
      - "./src/test/config/apache/vhost-app.conf:/etc/httpd/conf.d/vhost-app.conf:ro"
      - "./src/test/web/sources/htdocs:/DATA/app/htdocs"
      - "./src/test/web/sources/theme/217:/DATA/app/htdocs/css:ro"
      - "./logs/httpd:/var/log/httpd"
    ports:
      - "80:80"
    networks:
      - apache2-network


  fpm:
    image: php:7-fpm
    container_name: fpm7
    volumes:
      - "./src/test/web/sources/htdocs:/DATA/app/htdocs"
      - "./src/test/web/sources/theme/217:/DATA/app/htdocs/css:ro"
      - "./src/test/config/fpm-app.conf:/usr/local/etc/php-fpm.d/www.conf:ro"
#      - "./logs/fpm/:/var/log/fpm/"
    ports:
      - "9000:9000"
    networks:
      - apache2-network

networks:
  apache2-network:
